### ISSUE TITLE
[BUG] The function under aws-lambda-mongodb-atlas is not idempotent

### ISSUE THREAD

**Issue by Nsupyq** [mattwelke/serverless-managed-dbs-examples#135]
The function of writing pets  in [index.js](https://github.com/mattwelke/serverless-managed-dbs-examples/blob/master/aws-lambda-mongodb-atlas/handler.js#L42-L47) under aws-lambda-mongodb-atlas is not idempotent and may  insert multiple extra pets.

```
const newPet = getPet();
return {
    insertedPet: newPet,
    mongoResult: await pets.insertOne(newPet),
};
```

The primary key in mongodb is `_id`. Every time `pets.insertOne(newPet)` is invoked, it will generate a random `_id` and create a new record with that `_id` in mongodb. Thus, if the function fails after executing `pets.insertOne(newPet)`, AWS Lambda will [retry](https://docs.aws.amazon.com/lambda/latest/dg/invocation-retries.html) it and inserts a new pet again. Then even if the client invokes the function only once, there will be multiple new pets in database.

This can be fixed by making the function [idempotent](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-function-idempotent/). The function should use the [`awsRequestId`](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-context.html) provided by AWS Lambda to be `_id`. Then the function will insert only one new pet even if `pets.insertOne(newPet)` is retried.

**Comment by mattwelke** [comment]
This is okay. The example is only meant to show how to interact with MongoDB Atlas from AWS Lambda.
